// Code generated by "codegen -type int ./internal/pkg/code"; DO NOT EDIT.

package code

// init register error codes defines in this source code to `pkg/component-base/errors`
func init() {
	register(ErrSuccess, 200, "OK.")
	register(ErrUnknown, 500, "Internal server error.")
	register(ErrBind, 400, "Error occurred while binding the request body to the struct.")
	register(ErrValidation, 400, "Validation failed.")
	register(ErrTokenInvalid, 401, "Token invalid.")
	register(ErrPageNotFound, 404, "Page not found.")
	register(ErrObjectNotFound, 200, "Record not found.")
	register(ErrService, 200, "Service exception.")
	register(ErrDatabase, 500, "Database error.")
	register(ErrEncrypt, 401, "Error occurred while encrypting the user password.")
	register(ErrSignatureInvalid, 401, "Signature is invalid.")
	register(ErrExpired, 401, "Token expired.")
	register(ErrInvalidAuthHeader, 401, "Invalid authorization header.")
	register(ErrMissingHeader, 401, "The `Authorization` header was empty.")
	register(ErrPasswordIncorrect, 401, "Password was incorrect.")
	register(ErrPermissionDenied, 403, "Permission denied.")

}
